In [11]:
import numpy
n=numpy.arange(27)

In [ ]:
n.reshape(3,3,3)

In [13]:
import cv2

In [ ]:
img=cv2.imread("smallgray.png",1)
# 1 for blue,green,red on OpenCV
img

In [20]:
img=cv2.imread("smallgray.png",0) 
# 0 for grayscale
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
cv2.imwrite("newsmallgray.png", img)

True

In [22]:
img[0:2,2:4 ]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [23]:
img[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [26]:
for i in img:
  print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [ ]:
for i in img.flat:
  print(i)

In [36]:
img=cv2.imread("smallgray.png",0) 
# 0 for grayscale
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [37]:
 img1=numpy.hstack((img,img))

In [38]:
print(img1)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [39]:
img1=numpy.vstack((img,img))
print(img1)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [ ]:
lst=numpy.vsplit(img1,3)
lst